<?php
/**
 * Created by PhpStorm.
 * User: christmas
 * Date: 08/05/18
 * Time: 21:25
 */

namespace CDC\Loja\Test;

require "./vendor/autoload.php";

use PHPUnit_Framework_TestCase as PHPUnit;

class TestCase extends PHPUnit
{
    protected function setUp()
    {
        parent::setUp();
    }

    protected function tearDown()
    {
        parent::tearDown(); // TODO: Change the autogenerated stub
    }
}